### ISSUE TITLE
Bootstrap - User registration form

### ISSUE THREAD

**Issue by shorodilov** [edu-python-course/blog-bootstrap#14]

**Comment by saniyasharma123** [comment]
Choose from a wide range of Cyber security courses offered from CETPA Infotech. Ensure your organization's security with our comprehensive [online cyber security training](https://www.cetpainfotech.com/technology/cyber-security-training). Learn best practices from experts to protect your data and systems!
[summer training in Noida](https://www.cetpainfotech.com/summer-training)
